name: Build Release
on: [push]
permissions:
  contents: write
  discussions: write
jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      tex: ${{ steps.filter.outputs.tex }}
      workflows: ${{ steps.filter.outputs.workflows }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          tex:
            - '*.tex'
          workflows:
            - '.github/workflows/**'
  build_latex:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: ${{ (needs.paths-filter.outputs.tex == 'true') || (needs.paths-filter.outputs.workflows == 'true') }}
    continue-on-error: true
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: true
          continue-on-error: true
          root_file: mss.tex
          extra_system_packages: "inkscape"
          args: -f -jobname=mss -pdf -file-line-error -shell-escape -interaction=nonstopmode -synctex=1
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: mss.pdf
          retention-days: 1
  create_release:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: PDF
      - name: Get time
        id: time
        run: echo "::set-output name=time::$(TZ='Europe/Moscow' date +'%H:%M')"
      - name: Get date
        id: date
        run: echo "::set-output name=date::$(TZ='Europe/Moscow' date +'%d.%m.%Y')"
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          name: PDF ${{ steps.date.outputs.date }} ${{ steps.time.outputs.time }}
          body: ${{ steps.time.outputs.time }} - ${{github.event.head_commit.message}}
          append_body: true
          tag_name: ${{ steps.date.outputs.date }} # в рамках одного дня коммиты будут сливаться в один релиз
          files: |
            mss.pdf
